name: make

on:
  push:
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'
    branches: [ master, parser, builtin ]
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'
    branches: [ master, parser, builtin ]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git submodule
        run: git submodule update --init
      - name: all
        run: make all
      - name: clean
        run: make clean
      - name: re
        run: make re
      - name: fclean
        run: make fclean
