name: make

on:
  push:
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'
    branches: [ master ]
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'
    branches: [ master ]

jobs:
  make:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: git submodule
        run: git submodule update --init
      - name: all
        run: make all
      - name: clean
        run: make clean
      - name: re
        run: make re
      - name: fclean
        run: make fclean
      - name: install libcheck
        run: brew install check
      - name: running unit tests
        run: make test
